---
- name: Ensure blacklisted packages are not installed.
  become: true
  pacman:
    name: "{{ pacman_uninstalled_packages }}"
    state: absent

- name: Install configured pacman packages.
  become: true
  pacman:
    name: "{{ pacman_installed_packages }}"
    state: present
